---
apiVersion: v1
kind: Secret
metadata:
  name: jaeger-cassandra
  labels:
    app.kubernetes.io/name: jaeger
    helm.sh/chart: jaeger-0.17.4
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: jaeger
type: Opaque
data:
  password: "cGFzc3dvcmQ="

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-cassandra
  labels:
    app: cassandra
    chart: cassandra-0.15.2
    release: jaeger
    heritage: Tiller
spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: intra
    port: 7000
    targetPort: 7000
  - name: tls
    port: 7001
    targetPort: 7001
  - name: jmx
    port: 7199
    targetPort: 7199
  - name: cql
    port: 9042
    targetPort: 9042
  - name: thrift
    port: 9160
    targetPort: 9160
  selector:
    app: cassandra
    release: jaeger