apiVersion: authentication.istio.io/v1alpha1
kind: MeshPolicy
metadata:
  labels:
    operator.istio.io/component: Pilot
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.5.4
    release: istio
  name: default
spec:
  peers:
  - mtls:
      mode: STRICT